variables:
    CI_DEBUG_TRACE: "true"
    TEST_VAR: 4
    
always-run:
  script: echo 'this should always run'

on-pull-requests:
  script: echo 'this should run on pull requests'
  only:
    - external_pull_requests