variables:
    CI_DEBUG_TRACE: "false"
    TEST_VAR: 7
    
always-run:
  script: echo 'this should always run'

on-pull-requests:
  script: echo 'this should run on pull requests'
  only:
    - external_pull_requests

except-pull-requests:
  script: echo 'this should on everything EXCEPT pull requests'
  except:
    - external_pull_requests
