variables:
    CI_DEBUG_TRACE: "false"
    
on-pull-requests:
  script: 
    - echo 'this should run on pull requests...'
    - echo $CI_EXTERNAL_PULL_REQUEST_IID
    - echo $CI_PIPELINE_SOURCE
  only:
    - external_pull_requests

except-pull-requests:
  script: 
    - echo 'this should on everything EXCEPT pull requests.'
    - echo $CI_EXTERNAL_PULL_REQUEST_IID
    - echo $CI_PIPELINE_SOURCE
  except:
    - external_pull_requests
